# Generated by Django 5.1.5 on 2025-02-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_signup_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="board_images/"),
        ),
        migrations.AddField(
            model_name="board",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_boards", to="planner.signup"
            ),
        ),
    ]
